mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.choleece.base.springboot.mybatis.entity
  global-config:
    db-config:
      # 主键类型  配置详情见 com.baomidou.mybatisplus.annotation
      id-type: assign_id
      # mp2.3+ 全局表前缀 mp_
      # table-prefix: mp_
      #刷新mapper 调试神器
      refresh-mapper: true
      # 数据库大写下划线转换
      # capital-mode: true
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
      insert-strategy: default
      select-strategy: default
      update-strategy: default
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl